# Generated by Django 2.1.15 on 2020-09-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='req',
            field=models.IntegerField(default=5),
        ),
    ]
