# Generated by Django 2.1.15 on 2020-09-02 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20200901_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.ExtendedUser'),
        ),
    ]
