# Generated by Django 2.1.15 on 2020-09-02 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20200902_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestion',
            old_name='username',
            new_name='user',
        ),
    ]
