# Generated by Django 2.1.15 on 2020-09-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20200902_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
