# Generated by Django 2.1.15 on 2020-09-04 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_extendeduser_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.ExtendedUser')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.ExtendedUser')),
            ],
        ),
        migrations.AddField(
            model_name='suggestion',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='movie.Group'),
        ),
    ]
